export const POSTER_ACTION_TYPES  = {
    FETCH_POSTER_START : 'poster/FETCH_POSTER_START',
    FETCH_POSTER_SUCCESS : 'poster/FETCH_POSTER_SUCCESS',
    FETCH_POSTER_FAILED : 'poster/FETCH_POSTER_FAILED'
}


